// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Store.DataAccess;

#nullable disable

namespace Store.DataAccess.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240709165952_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Store.DataAccess.Entities.BasketEntity", b =>
                {
                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<string>("JsonProducts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<bool>("Sealed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("BasketId")
                        .HasName("basket_pk");

                    b.ToTable("Basket", (string)null);
                });

            modelBuilder.Entity("Store.DataAccess.Entities.BasketProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("Count");

                    b.HasKey("ProductId", "BasketId");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketProduct", (string)null);
                });

            modelBuilder.Entity("Store.DataAccess.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("Price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ProductId")
                        .HasName("product_pk");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Store.DataAccess.Entities.BasketProductEntity", b =>
                {
                    b.HasOne("Store.DataAccess.Entities.BasketEntity", "BasketEntity")
                        .WithMany("BasketProducts")
                        .HasForeignKey("BasketId")
                        .IsRequired()
                        .HasConstraintName("basketproduct_basket_fk");

                    b.HasOne("Store.DataAccess.Entities.ProductEntity", "ProductEntity")
                        .WithMany("BasketProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("basketproduct_product_fk");

                    b.Navigation("BasketEntity");

                    b.Navigation("ProductEntity");
                });

            modelBuilder.Entity("Store.DataAccess.Entities.BasketEntity", b =>
                {
                    b.Navigation("BasketProducts");
                });

            modelBuilder.Entity("Store.DataAccess.Entities.ProductEntity", b =>
                {
                    b.Navigation("BasketProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
